#This flag will tell Helm to install postgres
store:
  enabled: true  

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: INGRESSID

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
  - host: shercolorweb.ingress.lb0020.sites.sherwin.com
    paths:
      - path: /
        pathType: Prefix
  - host: shercolorweb.ingress.local.sites.sherwin.com
    paths:
      - path: /
        pathType: Prefix  
  tls:
  - hosts:
    - shercolorweb.ingress.lb0020.sites.sherwin.com
    - shercolorweb.ingress.local.sites.sherwin.com
    secretName: shercolorweb-tls-secrets

# Values for the postgresql dependency chart
postgresql:
  global:
    imageRegistry: docker.artifactory.sherwin.com
    storageClass: "longhorn"
    postgresql:
      postgresqlDatabase: "sherd"
      postgresqlUsername: "shercolor"
      existingSecret: "shercolorweb-secret"
      servicePort: "5432"
  image:
    registry: docker.artifactory.sherwin.com
    tag: 14.1.0-debian-10-r9
  service:
    type: LoadBalancer
    annotations: {metallb.universe.tf/allow-shared-ip: 172-30-0-8}
    loadBalancerIP: "172.30.0.8"
    externalTrafficPolicy: Cluster
  persistence:
    existingClaim: data-shercolor-postgres-postgresql-0
    size: 4Gi  

dbPostgresUrl: "jdbc:postgresql://shercolorweb-postgresql-headless.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.global.postgresql.servicePort }}/{{ .Values.postgresql.global.postgresql.postgresqlDatabase }}"
springProfilesActive: "{{ $environment }},postgres"  
dbUsername: "{{ .Values.postgresql.global.postgresql.postgresqlUsername }}"
