
service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: INGRESSID

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
  - host: shercolorweb.ingress.lb0020.sites.sherwin.com
    paths:
      - path: /
        pathType: Prefix
  - host: shercolorweb.ingress.local.sites.sherwin.com
    paths:
      - path: /
        pathType: Prefix  
  tls:
  - hosts:
    - shercolorweb.ingress.lb0020.sites.sherwin.com
    - shercolorweb.ingress.local.sites.sherwin.com
    secretName: shercolorweb-tls-secrets
    