
ingress:
  namespace: dev-shercolor
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSID"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  hosts:
  - host: shercolorweb.np-rancher.sherwin.com
    http:
      paths:
      - backend:
          service:
            name: shercolorweb
            port:
              number: 8090
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - shercolorweb.np-rancher.sherwin.com

dbPostgresUrl: "jdbc:postgresql://loadbalancer.lb0020.sites.sherwin.com:5432/sherd?currentSchema=shercolor"   
springProfilesActive: "{{ $environment }},oracle"
dbUsername: '{{ index .Values $environment "dbOracleUsername" }}'

dev:
  dbOracleUrl: "jdbc:oracle:thin:@SHERD_DBHOST.sherwin.com:1521/sherd"
  dbOracleUsername: "shercolor"
qa:
  dbOracleUrl: "jdbc:oracle:thin:@SHERQ_DBHOST.sherwin.com:1521/sherq"
  dbOracleUsername: "SHERCOLOR_USER"
prod:
  dbOracleUrl: "jdbc:oracle:thin:@SHERP_DBHOST.sherwin.com:1521/sherp"
  dbOracleUsername: "SHERCOLOR_USER"  