FROM openjdk:8-jre-slim
COPY mvnw mvnw
COPY .mvn .mvn
COPY pom.xml pom.xml
#RUN ./mvnw -B dependency:resolve dependency:resolve-plugins
COPY wildfly wildfly
COPY src src
ENTRYPOINT ./mvnw -B wildfly-jar:dev-watch