#logging:
#  config: classpath:log4j2-elk.xml
#
#---
spring:
  config:
    activate:
      on-profile: dev
    import: vault://shercolor/kv2/shercolorweb/dev
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-np-internal
        role: k8s-np-internal-shercolor-dev

---
spring:
  config:
    activate:
      on-profile: qa
    import: vault://shercolor/kv2/shercolorweb/qa
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-np-internal
        role: k8s-np-internal-shercolor-qa

---
spring:
  config:
    activate:
      on-profile: prod
    import: vault://shercolor/kv2/shercolorweb/prod
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-pr-internal
        role: k8s-pr-internal-shercolor-prod
