spring:
  config:
    activate:
      on-profile: dev
    import: vault://shercolor/kv2/shercolorweb/dev
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-np-dmz
        role: k8s-np-dmz-shercolor-dev

---
spring:
  config:
    activate:
      on-profile: qa
    import: vault://shercolor/kv2/shercolorweb/qa
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-np-dmz
        role: k8s-np-dmz-shercolor-qa

---
spring:
  config:
    activate:
      on-profile: prod
    import: vault://shercolor/kv2/shercolorweb/prod
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-pr-dmz
        role: k8s-pr-dmz-shercolor-prod
