spring:
  config:
    import: vault://
  cloud:
    vault:
      authentication: APPROLE
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: shercolor/kv2
      approle:
        role-id: 4b851bc5-133f-c30f-b8f7-d560a3a46fa9
        secret-id: 105e90e5-cfd3-bf1a-36e8-a10260029ac8