spring:
  config:
    activate:
      on-profile: dev
    import: vault://tag/shercolor/kv2/dev/shercolorweb
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: tag/shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-np-internal
        role: k8s-np-internal-shercolor-dev

---
spring:
  config:
    activate:
      on-profile: qa
    import: vault://tag/shercolor/kv2/qa/shercolorweb
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: tag/shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-np-internal
        role: k8s-np-internal-shercolor-qa

---
spring:
  config:
    activate:
      on-profile: prod
    import: vault://tag/shercolor/kv2/prod/shercolorweb
  cloud:
    vault:
      authentication: KUBERNETES
      uri: https://vault.sherwin.com
      application-name: shercolorweb
      kv:
        backend: tag/shercolor/kv2
      kubernetes:
        kubernetes-path: kubernetes-pr-internal
        role: k8s-pr-internal-shercolor-prod
