server:
  display-name: SherColorWeb
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

spring:
  config:
    import: optional:file:${user.home}/dev.properties
  profiles:
      # login profile is unconditionally included in order to use the Wildfly security JNDI connection
      include: login,common
      # activate db type (oracle or postgres) and environment (dev, qa or prod)
      active: oracle,dev,local

logging:
  pattern:
    console: "%d{'dd/MMM/yyyy HH:mm:ss', EST} %-4level %C{3}.%M:%L - %m%n"
  level:
    org.hibernate.SQL: error
    org.hibernate: error
    org.apache.struts: warn
    com.opensymphony.xwork2: warn