server:
  display-name: SherColorWeb
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
spring:
  datasource:
    password: ${dbPassword}
    username: ${dbUsername}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS
  profiles:
      # login profile is always unconditionally included in order to use Wildfly security JNDI connection
      include: login
      # activate db type (oracle or postgres) and environment (dev, qa or prod)
      # The login-test profile is needed to tell Spring to use a JDBC connection for SherColorLogin
      # instead of the Wildfly JNDI connection for testing. These can be overridden via command-line args or env variables
      active: oracle,dev,login-test
