{{- $environment := .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data: 
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfilesActive }}
  dbUsername: {{ .Values.dbUsername }}
  dbPostgresUrl: {{ .Values.dbPostgresUrl }}
  oeBaseUrl: {{ .Values.oeBaseUrl | quote }}
  dbOracleUrl: {{ index .Values $environment "dbOracleUrl" | quote }}
  sherlinkLoginUrl: {{ index .Values $environment "sherlinkLoginUrl" | quote }}
  sherlinkTokenSwUrl: {{ index .Values $environment "sherlinkTokenSwUrl" | quote }}