{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/common-name: shercolorweb.ingress.lb0020.sites.sherwin.com
    cert-manager.io/cluster-issuer: vault-issuer
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSID"
#    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
#    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  name: ingress
  namespace: default
  #namespace: dev-shercolor
  labels:
    {{- include "shercolorweb.selectorLabels" . | nindent 8 }}
spec:
  rules:
#  - host: shercolorweb.np-rancher.sherwin.com
  - host: shercolorweb.ingress.lb0020.sites.sherwin.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
  - host: shercolorweb.ingress.local.sites.sherwin.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
  tls:
  - secretName: shercolorweb-tls-secrets
    hosts:
#    - shercolorweb.np-rancher.sherwin.com
    - shercolorweb.ingress.lb0020.sites.sherwin.com
    - shercolorweb.ingress.local.sites.sherwin.com
{{- end }}
