{{- $environment := .Values.env -}}
{{- $pass := randAlphaNum 16 | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  # Randomize the password, but make it available as a secret 
  # for workloads to use
  {{- if .Values.store.enabled }}
  dbPassword: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}
  postgresql-password: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}
  postgresql-postgres-password: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}
  {{- else }}
  dbPassword: {{ index .Values $environment "dbOraclePassword" | b64enc }}  
  {{- end }}