{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  # Randomize the password, but make it available as a secret 
  # for workloads to use
  {{- if .Values.store.enabled }}
  {{ .Values.postgresql.global.postgresql.auth.secretKeys.userPasswordKey }}: {{ .Values.postgres.shercolorPass | b64enc }}
  sherlinkDbPassword: {{ .Values.sherlinkDbPassword }}
  {{- end }}
{{- end }}