apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  # Randomize the password, but make it available as a secret 
  # for workloads to use
  {{- if .Values.store.enabled }}
  {{- $pass := randAlphaNum 16 | b64enc }}
  dbPassword: {{ $pass }}
  postgresqlPassword: {{ $pass }}
  postgresqlAdminPassword: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
  {{- else }}
  dbPassword: {{ .Values.dbOraclePassword | b64enc }}  
  {{- end }}