{{- $environment := .Values.env -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  # Randomize the password, but make it available as a secret 
  # for workloads to use
  password: {{ randAlphaNum 16 | b64enc }}