apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "shercolorweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "shercolorweb.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport
spec:
  type: NodePort
  selector:
    {{- include "shercolorweb.selectorLabels" . | nindent 4 }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8090
      targetPort: 8090
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31000