apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "shercolorweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "shercolorweb.selectorLabels" . | nindent 4 }}

{{- if .Values.service.nodeport.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport
spec:
  type: NodePort
  selector:
    {{- include "shercolorweb.selectorLabels" . | nindent 4 }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31000 

{{- end }}

