server:
  display-name: SherColorWeb
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
spring:
  config:
    import: /web_apps/server/shercolor/deploy/shercolorcommonnew.properties
  datasource:
    password: ${jdbc.password.${dbEnv}}
    username: ${jdbc.username.${dbEnv}}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS
  profiles:
      #either oracle or postgres
      include: oracle,login
