# Run Qualys DAST scan when a release branch is made or by manual trigger
name: Run Qualys DAST Scan
on:
  create:
  workflow_dispatch:
    inputs:
        release_version:
            description: "Release Version"
            required: true
            default: "X.Y.Z"

jobs:
  dast-security-scan:
    if: ${{ contains(github.ref, 'refs/heads/release/') }}
    uses: sherwin-williams-co/colorex-actions/.github/workflows/dast-security-scan-workflow.yml@master
    secrets:
      SHERCOLOR_ORCA_API_KEY: ${{ secrets.SHERCOLOR_ORCA_API_KEY }}
      ORCA_QUALYS_CONFIG_ID: ${{ secrets.ORCA_QUALYS_CONFIG_ID }}
