#Executes on merge of each PR to development
name: Deploy to DEV & QA
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dja557/spring-boot-wildfly-bootable-k8s
#       - development
#       - master
#       - 'release/**'
    types: [closed]
    
jobs:
  dev-qa-deploy:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/dev-qa-deploy-workflow.yml@dja557/SCD-59
    with:
      java_version: 8
      app_version: ${{ needs.get-app-version.outputs.ARTIFACT_VERSION }}
      chart_directory: shercolorweb-chart
      dev_helm_values_files: '["values.yaml","values-rancher-dev.yaml"]'
      qa_helm_values_files: '["values.yaml","values-rancher-qa.yaml"]'
    secrets: inherit
#       DEV_URL: ${{ secrets.DEV_URL }}
#       QA_URL: ${{ secrets.QA_URL }}
#       ARTIFACTORY_REGISTRY: ${{ secrets.ARTIFACTORY_REGISTRY }}
#       ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
#       ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
#       KUBE_CONFIG_NP_RANCHER: ${{ secrets.KUBE_CONFIG_NP_RANCHER }}
