#Executes on merge of each PR to development
name: Publish Snapshot
on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
      - master
      - 'release/**'
    types: [closed]
    
jobs:
  snapshot-publish:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/dev-qa-deploy-workflow.yml@dja557/SCD-59
    with:
      java_version: 8
    secrets:
      ARTIFACTORY_REGISTRY: ${{ secrets.ARTIFACTORY_REGISTRY }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
