name: Image Build & Deploy to DEV
on:
  workflow_dispatch:
  repository_dispatch:
    types: [shercolorweb-build-deploy]
  pull_request:
    branches:
      - development
      - master
      - release/*
    types: [ closed ]
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - '.gitignore'

    
jobs:
  image-build-dev-deploy:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/image-build-deploy-workflow.yml@dja557/SCD-722
    with:
      java_version: '8'
      deploy_env_name: 'dev'
      chart_directory: shercolorweb-chart
      release_name: shercolorweb
      deploy_url: 'https://dev-shercolor.np-dmz-rancher.sherwin.com/shercolorweb'
      helm_lint_values: '"values.yaml" "values-local.yaml"'
      deploy_helm_values: '"values.yaml" "values-rancher-dmz-dev.yaml"'
      kube_config_secret_name: 'KUBE_CONFIG_NP_DMZ_RANCHER'
    secrets: inherit
