name: Validate Pull Request
on:
  workflow_dispatch:
  push:
    branches: development
  pull_request:
    branches: 
      - development
      - master
      - release/*

    types: [opened, synchronize]
    paths-ignore: 
    - '.github/**'
    - '**/*.md'
    - '.gitignore'
      
jobs:
  pr-validation:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/pr-validation-workflow.yml@master
    with:
      java_version: 8
    secrets: inherit
