name: Validate Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - development
      - master
      - release/*

    types: [opened, synchronize]
    paths-ignore: 
      - '**.md'
      - '.gitignore'
      
jobs:
  analyze:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/codeql-workflow.yml@dja557/SCD-376
    with:
      java_version: 8
      codeql_languages: "['java']"
    secrets: inherit

  pr-validation:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/pr-validation-workflow.yml@dja557/SCD-376
    with:
      java_version: 8
      codeql_languages: 'java, javascript'
    secrets: inherit
