name: Validate Pull Request
on:
  pull_request:
    branches: 
      - development
      - master
      - 'release/**'
    types: [opened, synchronize]
    paths-ignore: 
      - '**.md'
      - '.gitignore'
      
jobs:
  pr-validation:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/pr-validation-workflow.yml@master
    with:
      java_version: 8
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
      SHERCOLOR_SONAR_TOKEN: ${{ secrets.SHERCOLOR_SONAR_TOKEN }}
      SHERCOLOR_SONAR_HOST_URL: ${{ secrets.SHERCOLOR_SONAR_HOST_URL }}
      SHERCOLOR_VERACODE_API_ID: ${{ secrets.SHERCOLOR_VERACODE_API_ID }}
      SHERCOLOR_VERACODE_API_KEY: ${{ secrets.SHERCOLOR_VERACODE_API_KEY }}
