name: Promote QA to PROD
on:
  pull_request:
#     branches:
#       - dja557/spring-boot-wildfly-bootable-k8s
# #       - development
# #       - master
# #       - 'release/**'
#     types: [closed]
  workflow_dispatch:

jobs:
  prod-promote:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/prod-promotion-workflow.yml@dja557/SCD-59
    with:
      chart_directory: shercolorweb-chart
      release_name: shercolorweb
      prod_helm_values: '"values.yaml" "values-rancher-prod.yaml"'
      prod_url: 'https://shercolor.sherwin.com/shercolorweb'
    secrets: inherit
