name: Promote DEV to QA
on: workflow_dispatch
  
jobs:
  qa-deploy:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/qa-promotion-workflow.yml@master
    with:
      release_name: shercolorweb
      qa_url: 'https://qa-shercolor.np-dmz-rancher.sherwin.com/shercolorweb'
      qa_helm_values: '"values.yaml" "values-rancher-dmz-qa.yaml"'
      kube_config_secret_name: 'KUBE_CONFIG_NP_DMZ_RANCHER'
    secrets: inherit
