name: Publish/Tag Release
on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java Version (https://github.com/actions/setup-java#supported-version-syntax)'
        type: string
        default: '8'
        required: false
      release_version:
        description: "Release Version"
        required: true
        default: "X.Y.Z"
      development_version:
        description: "New Development Version"
        required: true
        default: "X.Y.Z-SNAPSHOT"
        
jobs:
  release:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/release-publish-workflow.yml@master
    with:
      java_version: ${{ github.event.inputs.java_version }}
      release_version: ${{ github.event.inputs.release_version }}
      development_version: ${{ github.event.inputs.development_version }}
    secrets: inherit
