# Run Veracode SAST scan on PR approval or by addition of PR label to re-trigger
name: Run Veracode SAST Policy Scan
on:
  pull_request_review:
    types: [submitted]
    paths-ignore: 
    - '.github/**'
    - '**/*.md'
    - '.gitignore'
  pull_request:
    types: [labeled]
    paths-ignore: 
      - '.github/**'
      - '**/*.md'
      - '.gitignore'
    
jobs:
  sast-security-scan:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/sast-security-scan-workflow.yml@master
    with:
      java_version: 8
    secrets: inherit
