# Run Veracode SAST scan on PR approval or by addition of PR label to re-trigger
name: Run Veracode SAST Policy Scan
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [labeled]
    
jobs:
  sast-security-scan:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/sast-security-scan-workflow.yml@master
    with:
      java_version: 8
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
      SHERCOLOR_ORCA_API_KEY: ${{ secrets.SHERCOLOR_ORCA_API_KEY }}
      ORCA_VERACODE_CONFIG_ID: ${{ secrets.ORCA_VERACODE_CONFIG_ID }}
