#Executes on merge of each PR to development, publishes SNAPSHOT to artifactory
name: Publish Snapshot
on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
      - master
      - release/*
    types: [closed]
    
jobs:
  snapshot-publish:
    uses: sherwin-williams-co/colorex-actions/.github/workflows/snapshot-publish-workflow.yml@master
    with:
      java_version: 8
    secrets: inherit
