-- Table CustWebDealer
CREATE TABLE "SHERCOLOR"."CUSTWEBDEALER" 
   (	"CUSTOMERID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"DEALERNAME" VARCHAR2(30 BYTE), 
	"DLRPHONENBR" VARCHAR2(20 BYTE), 
	"DLRHOMESTORE" NUMBER(*,0), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	  PRIMARY KEY ("CUSTOMERID"));

  CREATE INDEX "SHERCOLOR"."DEALERNAME" ON "SHERCOLOR"."CUSTWEBDEALER" ("DEALERNAME");

  CREATE INDEX "SHERCOLOR"."DLRPHONENBR" ON "SHERCOLOR"."CUSTWEBDEALER" ("DLRPHONENBR");