-- Table CustWebDealerCust
 CREATE TABLE "SHERCOLOR"."CUSTWEBDEALERCUST" 
   (	"CUSTOMERID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"DLRCUSTID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DLRCUSTNAME" VARCHAR2(30 BYTE), 
	"DLRCUSTADDRESS" VARCHAR2(30 BYTE), 
	"DLRCUSTCITY" VARCHAR2(20 BYTE), 
	"DLRCUSTSTATE" VARCHAR2(2 BYTE), 
	"DLRCUSTZIP" VARCHAR2(6 BYTE), 
	"DLRCUSTCOUNTRY" VARCHAR2(20 BYTE), 
	"DLRCUSTPHONENBR" VARCHAR2(20 BYTE), 
	"DLRCUSTCONTACT" VARCHAR2(30 BYTE), 
	"DATEADDED" DATE, 
	"DATEUPDATED" DATE, 
	"UPDATEUSER" VARCHAR2(6 BYTE), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	  PRIMARY KEY ("CUSTOMERID", "DLRCUSTID"));

  CREATE INDEX "SHERCOLOR"."CUSTCITY" ON "SHERCOLOR"."CUSTWEBDEALERCUST" ("CUSTOMERID", "DLRCUSTCITY");

  CREATE INDEX "SHERCOLOR"."CUSTCONTACT" ON "SHERCOLOR"."CUSTWEBDEALERCUST" ("CUSTOMERID", "DLRCUSTCONTACT");

  CREATE INDEX "SHERCOLOR"."CUSTNAME" ON "SHERCOLOR"."CUSTWEBDEALERCUST" ("CUSTOMERID", "DLRCUSTNAME");

  CREATE INDEX "SHERCOLOR"."CUSTPHONENBR" ON "SHERCOLOR"."CUSTWEBDEALERCUST" ("CUSTOMERID", "DLRCUSTPHONENBR");

  CREATE INDEX "SHERCOLOR"."CUSTSTATE" ON "SHERCOLOR"."CUSTWEBDEALERCUST" ("CUSTOMERID", "DLRCUSTSTATE");