
  CREATE TABLE "SHERCOLOR"."CUSTWEBECAL" 
   (	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"COLORANTID" VARCHAR2(5 BYTE), 
	"TINTERMODEL" VARCHAR2(25 BYTE), 
	"TINTERSERIAL" VARCHAR2(15 BYTE), 
	"UPLOADDATE" VARCHAR2(10 BYTE), 
	"UPLOADTIME" VARCHAR2(4 BYTE), 
	"FILENAME" VARCHAR2(50 BYTE), 
	"DATA" BLOB, 
	 PRIMARY KEY ("FILENAME");

  CREATE INDEX "SHERCOLOR"."CUSTECAL_IDX1" ON "SHERCOLOR"."CUSTWEBECAL" ("CUSTOMERID", "COLORANTID", "TINTERMODEL", "TINTERSERIAL", "UPLOADDATE", "UPLOADTIME")
   TABLESPACE "SHERCOLOR";