-- Table CustWebDealerCustOrd
 CREATE TABLE "SHERCOLOR"."CUSTWEBDEALERCUSTORD" 
   (	"CUSTOMERID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"DLRCUSTID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CONTROLNBR" NUMBER(*,0), 
	"CUSTORDERNBR" VARCHAR2(20 BYTE), 
	"DATEADDED" DATE, 
	"DATEUPDATED" DATE, 
	"UPDATEUSER" VARCHAR2(6 BYTE), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	  PRIMARY KEY ("CUSTOMERID", "DLRCUSTID", "CONTROLNBR"));

  CREATE INDEX "SHERCOLOR"."CUSTORDERNBR" ON "SHERCOLOR"."CUSTWEBDEALERCUSTORD" ("CUSTOMERID", "DLRCUSTID", "CUSTORDERNBR");
