CREATE TABLE SHERCOLOR.CustWebParms (	
	customerId        varchar2(20)         NOT NULL ENABLE, 
	SeqNbr            number(3,0)          NOT NULL ENABLE, 
	Abbrev            varchar2(5)                         ,
	StoreComp         varchar2(20)                        ,
	ColorComp         varchar2(20)                        ,
	ProdComp          varchar2(20)                        ,
	ClrntSysId        varchar2(5)                         ,
	Active            number(1,0) check (Active between 0 and 1),
	SwuiTyp           varchar2(10)                        ,
	SwuiTitle         varchar2(20)                        ,
	AltProdComp1      varchar2(20)                        ,
	AltProdComp2      varchar2(20)                        ,
	AltProdComp3      varchar2(20)                         ,
	AltProdComp4      varchar2(20)                        ,
	AltProdComp5      varchar2(20)                        ,
	AltColorComp1     varchar2(20)                        ,
	AltColorComp2     varchar2(20)                        ,
	AltColorComp3     varchar2(20)                        ,
	AltColorComp4     varchar2(20)                        ,
	AltColorComp5     varchar2(20)                        ,
	FormRule          varchar2(5)                         ,
	BulkDeep          number(1,0) check (BulkDeep between 0 and 1),
	BulkDn            varchar2(20)                        ,
	BulkUp            varchar2(20)                        ,
	BulkStart         varchar2(5)                         ,
	ColorPrime        number(1,0) check (ColorPrime between 0 and 1),
	OpacityCrtl       number(1,0) check (OpacityCrtl between 0 and 1),
	FormQtrShot       number(1,0) check (FormQtrShot between 0 and 1),
	TargetCr2         number(1,0) check (TargetCr2 between 0 and 1),
	LastUpd           date                                ,
	CdsAdlFld         varchar2(20)                        ,
CONSTRAINT CustWebParms_pk PRIMARY KEY (customerId, seqNbr));


