
  CREATE TABLE "SHERCOLOR"."CUSTWEBDEVICES" 
   (	"CUSTOMERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SERIALNBR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"DEVICETYPE" VARCHAR2(20 BYTE), 
	"DEVICEMODEL" VARCHAR2(20 BYTE),
	"SEQNBR" NUMBER(38,0) DEFAULT 1
   );
