CREATE TABLE SHERCOLOR.CustWebTranCorr (	
	CustomerId        varchar2(20)         NOT NULL ENABLE, 
	ControlNbr        number(7,0)          NOT NULL ENABLE, 
	LineNbr           number(3,0)          NOT NULL ENABLE,
	Cycle             number(3,0)          NOT NULL ENABLE,
	UnitNbr           number(3,0)          NOT NULL ENABLE,
	Step              number(3,0)          NOT NULL ENABLE,
	Reason            varchar2(100)                       , -- Too Red, Too Green, Too Light, Too Dark, etc.
	Status            varchar2(20)                        , -- Open, Accepted, Discarded, Keep Original, etc.
	UserId            varchar2(20)                        ,
	DateTime          timestamp(6) with time zone         ,
	CorrMethod        varchar2(20)                        , -- Manual Adjustment, Percent Adjustment, Color Eye Adjustment
	MergedWithOrig    number(1,0) default 0 check (MergedWithOrig between 0 and 1),
	ClrntSysId        varchar2(5)                         ,
	ShotSize          number(4,0)                         ,
	Clrnt1            varchar2(5)                         ,
	ClrntAmt1         number(7,0)                         ,
	Clrnt2            varchar2(5)                         ,
	ClrntAmt2         number(7,0)                         ,
	Clrnt3            varchar2(5)                         ,
	ClrntAmt3         number(7,0)                         ,
	Clrnt4            varchar2(5)                         ,
	ClrntAmt4         number(7,0)                         ,
	Clrnt5            varchar2(5)                         ,
	ClrntAmt5         number(7,0)                         ,
	Clrnt6            varchar2(5)                         ,
	ClrntAmt6         number(7,0)                         ,
	Clrnt7            varchar2(5)                         ,
	ClrntAmt7         number(7,0)                         ,
	Clrnt8            varchar2(5)                         ,
	ClrntAmt8         number(7,0)                         ,
CONSTRAINT CustWebTranCorr_pk PRIMARY KEY (CustomerId, ControlNbr, LineNbr, Cycle, UnitNbr, Step));