spring:
  jpa:
    format-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
    use-sql-comments: true
  main:
    web-application-type: none
  datasource:
    jndi-name: java:jboss/datasources/jboss.jdbc.pool.securityPool